### PR TITLE
older v1.5a2 version

### PR DESCRIPTION
**Pull request by step21**
For a specific project, I need exactly this version, even though technically it is listed as pre-release. If possible, please merge into a new v.1.5x branch.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by step21** [comment]
@conda-forge-admin please restart ci

**Comment by step21** [comment]
The only thing that sometimes still fails is travis, because it randomly runs out of disk space, which I had with other builds too. Otherwise, would be great if this could be added as a version.

**Comment by step21** [comment]
@conda-forge-admin please restart ci

**Comment by isuruf** [comment]
@step21, we don't merge alpha releases into the main label.

**Comment by step21** [comment]
Well I don't know what's special about it, but I know projects that use it in production, which is why I got the idea in the first place. And it just said pre-release (on pypi), does that mean alpha? So do you not merge them at all, or just somehow differently? (not sure what label refers to here)

**Comment by chrisburr** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

**Comment by nehaljwani** [comment]
```
gevent                         1.5a2  py36h733ef82_0  conda-forge/label/gevent_dev
gevent                         1.5a2  py36h7b7a099_0  conda-forge/label/gevent_dev
gevent                         1.5a2  py37h56d091d_0  conda-forge/label/gevent_dev
gevent                         1.5a2  py37hceb021f_0  conda-forge/label/gevent_dev
gevent                         1.5a2  py38h7631653_0  conda-forge/label/gevent_dev
gevent                         1.5a2  py39h0c9b5dc_0  conda-forge/label/gevent_dev
```

**Comment by step21** [comment]
thanks!

**Pull request closed without merging**
